---
apiVersion: v1
kind: Secret
metadata:
  name: quay-robot-account-secret
  namespace: pipelines-tutorial
  annotations:
    tekton.dev/docker-0: https://quay.io
type: kubernetes.io/basic-auth
stringData:
  username: ${USERNAME}
  password: ${PASSWORD}
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: petclinic-image-quay
spec:
  type: image
  params:
  - name: url
    value: quay.io/danhawker/spring-petclinic
